[profile.default]
solc_version = '0.8.28'
optimizer = true
optimizer_runs = 10_000
libs = ['node_modules']
remappings = ['@openzeppelin/=node_modules/@openzeppelin/']
src = 'src'
test = 'test'
script = 'script'
